app = 'broucurrenciesapi-cold-shadow-6325'
primary_region = 'gig'

[build]
  dockerfile = 'Dockerfile'

[env]
  GECKODRIVER_PATH = '/app/geckodriver'
  PYTHONUNBUFFERED = 'true'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
